using System.Collections.Generic;
using System.Windows.Data;
static class Constants
{
	public const int ParamsBlockLengthInBytes = 0xCF+1; //208 байт
	public const int SecondsInADay = 60*60*24;
	public const int LengthOfUnpackedArray = ParamsBlockLengthInBytes*SecondsInADay;
	public const int UnpackedParametersArrayLength = ParamsBlockLengthInBytes * SecondsInADay;
public static Dictionary<int,ParameterAllValues> ParameterData = new Dictionary<int,ParameterAllValues>()
{
  [0]= new ParameterAllValues {parameterName=ParameterName.ТП1, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой },
  [2]= new ParameterAllValues {parameterName=ParameterName.ТП2, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [4]= new ParameterAllValues {parameterName=ParameterName.ТП3, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [6]= new ParameterAllValues {parameterName=ParameterName.ТП4, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [8]= new ParameterAllValues {parameterName=ParameterName.ТП5, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [10]= new ParameterAllValues {parameterName=ParameterName.ТП6, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [12]= new ParameterAllValues {parameterName=ParameterName.ТП7, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [14]= new ParameterAllValues {parameterName=ParameterName.ТП8, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [16]= new ParameterAllValues {parameterName=ParameterName.ТП9, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [18]= new ParameterAllValues {parameterName=ParameterName.ТСМ_0, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [20]= new ParameterAllValues {parameterName=ParameterName.ТП11, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [22]= new ParameterAllValues {parameterName=ParameterName.ТП12, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [24]= new ParameterAllValues {parameterName=ParameterName.ТП13, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [26]= new ParameterAllValues {parameterName=ParameterName.ТП14, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [28]= new ParameterAllValues {parameterName=ParameterName.ТП15, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [30]= new ParameterAllValues {parameterName=ParameterName.ТП16, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [32]= new ParameterAllValues {parameterName=ParameterName.ТП17, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [34]= new ParameterAllValues {parameterName=ParameterName.ТП18, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [36]= new ParameterAllValues {parameterName=ParameterName.ТП19, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [38]= new ParameterAllValues {parameterName=ParameterName.ТСМ_1, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [40]= new ParameterAllValues {parameterName=ParameterName.ТП21, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [42]= new ParameterAllValues {parameterName=ParameterName.ТП22, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [44]= new ParameterAllValues {parameterName=ParameterName.ТСМ_2, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [46]= new ParameterAllValues {parameterName=ParameterName.ТСМ23, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [48]= new ParameterAllValues {parameterName=ParameterName.ТСМ24, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [50]= new ParameterAllValues {parameterName=ParameterName.ТСМ25, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [52]= new ParameterAllValues {parameterName=ParameterName.ТСМ26, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [54]= new ParameterAllValues {parameterName=ParameterName.ТСМ27, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [56]= new ParameterAllValues {parameterName=ParameterName.ТСМ28, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [58]= new ParameterAllValues {parameterName=ParameterName.ТСМ29, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [60]= new ParameterAllValues {parameterName=ParameterName.ТСМ30, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [62]= new ParameterAllValues {parameterName=ParameterName.ТСМ31, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [64]= new ParameterAllValues {parameterName=ParameterName.ТСМ32, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [66]= new ParameterAllValues {parameterName=ParameterName.ТСМ33, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [68]= new ParameterAllValues {parameterName=ParameterName.ТСМ34, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [70]= new ParameterAllValues {parameterName=ParameterName.ТСМ35, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [72]= new ParameterAllValues {parameterName=ParameterName.ТСМ36, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [74]= new ParameterAllValues {parameterName=ParameterName.ТСМ37, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [76]= new ParameterAllValues {parameterName=ParameterName.ТСМ38, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [78]= new ParameterAllValues {parameterName=ParameterName.ТСМ39, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [80]= new ParameterAllValues {parameterName=ParameterName.ТСМ40, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [82]= new ParameterAllValues {parameterName=ParameterName.ДБТ1, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [84]= new ParameterAllValues {parameterName=ParameterName.ДБТ2, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [86]= new ParameterAllValues {parameterName=ParameterName.ДБТ3, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [88]= new ParameterAllValues {parameterName=ParameterName.Iрд, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [90]= new ParameterAllValues {parameterName=ParameterName.Uрд, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [92]= new ParameterAllValues {parameterName=ParameterName.Rплавки, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [94]= new ParameterAllValues {parameterName=ParameterName.Rизол, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [96]= new ParameterAllValues {parameterName=ParameterName.Empty1, parameterType=ParameterType.неОпределён, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.НеОпределено},
  [98]= new ParameterAllValues {parameterName=ParameterName.Empty2, parameterType=ParameterType.неОпределён, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.НеОпределено},
  [100]= new ParameterAllValues {parameterName=ParameterName.CTR_100, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [102]= new ParameterAllValues {parameterName=ParameterName.Метран_2_5, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [104]= new ParameterAllValues {parameterName=ParameterName.ТСМ_41, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [106]= new ParameterAllValues {parameterName=ParameterName.Давление_водооборота, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [108]= new ParameterAllValues {parameterName=ParameterName.Угол_поворота_тигля, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [110]= new ParameterAllValues {parameterName=ParameterName.Метран_250, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [112]= new ParameterAllValues {parameterName=ParameterName.P_над_поршнем, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [114]= new ParameterAllValues {parameterName=ParameterName.P_под_поршнем, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [116]= new ParameterAllValues {parameterName=ParameterName.Положение_штока, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой},
  [118]= new ParameterAllValues {parameterName=ParameterName.Empty3, parameterType=ParameterType.неОпределён, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.НеОпределено},
  [120]= new ParameterAllValues {parameterName=ParameterName.Ток_общ, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой,parameterUnit=ParameterUnit.А},
  [122]= new ParameterAllValues {parameterName=ParameterName.Напряжение_дуги, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой,parameterUnit=ParameterUnit.В},
  [124]= new ParameterAllValues {parameterName=ParameterName.Расход_воды, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой,parameterUnit=ParameterUnit.м3_ч},
  [126]= new ParameterAllValues {parameterName=ParameterName.Вакуум, parameterType=ParameterType.аналоговый, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.ДваЗнакаПослеЗапятой,parameterUnit=ParameterUnit.мм_рт_ст,parameterUnitAlt=ParameterUnit.мм_рт_ст},
  [128]= new ParameterAllValues {parameterName=ParameterName.Empty4, parameterType=ParameterType.неОпределён, parameterSize=ParameterSize.ДваБайта,parameterScale=ParameterScale.НеОпределено},
  [1301]= new ParameterAllValues {parameterName=ParameterName.Ду500_130_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
  [1302]= new ParameterAllValues {parameterName=ParameterName.Ду500_130_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
  [1303]= new ParameterAllValues {parameterName=ParameterName.ДВН1500_130_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
  [1304]= new ParameterAllValues {parameterName=ParameterName.ДВН1500_130_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
  [1305]= new ParameterAllValues {parameterName=ParameterName.ДВН3000_130_5, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит5,colorBinding=new Binding("parameterState")},
  [1306]= new ParameterAllValues {parameterName=ParameterName.ДВН3000_130_6, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит6,colorBinding=new Binding("parameterState")},
  [1307]= new ParameterAllValues {parameterName=ParameterName.ARPw_130_7, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит7,colorBinding=new Binding("parameterState")},
  [1308]= new ParameterAllValues {parameterName=ParameterName.ARPw_130_8, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит8,colorBinding=new Binding("parameterState")},
  [1311]= new ParameterAllValues {parameterName=ParameterName.SZO_131_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
  [1312]= new ParameterAllValues {parameterName=ParameterName.SZO_131_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
  [1313]= new ParameterAllValues {parameterName=ParameterName.Ду160_131_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
  [1314]= new ParameterAllValues {parameterName=ParameterName.Ду160_131_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
  [1315]= new ParameterAllValues {parameterName=ParameterName.Ду160_131_5, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит5,colorBinding=new Binding("parameterState")},
  [1316]= new ParameterAllValues {parameterName=ParameterName.Ду160_131_6, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит6,colorBinding=new Binding("parameterState")},
  [1317]= new ParameterAllValues {parameterName=ParameterName.Ду500_131_7, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит7,colorBinding=new Binding("parameterState")},
  [1318]= new ParameterAllValues {parameterName=ParameterName.Ду500_131_8, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит8,colorBinding=new Binding("parameterState")},
  [1321]= new ParameterAllValues {parameterName=ParameterName.ДВН1500_132_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
  [1322]= new ParameterAllValues {parameterName=ParameterName.ДВН1500_132_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
  [1323]= new ParameterAllValues {parameterName=ParameterName.ДВН3000_132_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
  [1324]= new ParameterAllValues {parameterName=ParameterName.ДВН3000_132_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
  [1325]= new ParameterAllValues {parameterName=ParameterName.ARPw_132_5, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит5,colorBinding=new Binding("parameterState")},
  [1326]= new ParameterAllValues {parameterName=ParameterName.ARPw_132_6, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит6,colorBinding=new Binding("parameterState")},
  [1327]= new ParameterAllValues {parameterName=ParameterName.SZO_132_7, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит7,colorBinding=new Binding("parameterState")},
  [1328]= new ParameterAllValues {parameterName=ParameterName.SZO_132_8, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит8,colorBinding=new Binding("parameterState")},
  [1331]= new ParameterAllValues {parameterName=ParameterName.Ду160_133_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
  [1332]= new ParameterAllValues {parameterName=ParameterName.Ду160_133_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
  [1333]= new ParameterAllValues {parameterName=ParameterName.Ду160_133_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
  [1334]= new ParameterAllValues {parameterName=ParameterName.Ду160_133_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
  [1335]= new ParameterAllValues {parameterName=ParameterName.Ду500_133_5, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит5,colorBinding=new Binding("parameterState")},
  [1336]= new ParameterAllValues {parameterName=ParameterName.Ду500_133_6, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит6,colorBinding=new Binding("parameterState")},
  [1337]= new ParameterAllValues {parameterName=ParameterName.ДВН1500_133_7, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит7,colorBinding=new Binding("parameterState")},
  [1338]= new ParameterAllValues {parameterName=ParameterName.ДВН1500_133_8, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит8,colorBinding=new Binding("parameterState")},
  [1341]= new ParameterAllValues {parameterName=ParameterName.ДВН3000_134_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
  [1342]= new ParameterAllValues {parameterName=ParameterName.ДВН3000_134_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
  [1343]= new ParameterAllValues {parameterName=ParameterName.ARPw_134_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
  [1344]= new ParameterAllValues {parameterName=ParameterName.ARPw_134_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
  [1345]= new ParameterAllValues {parameterName=ParameterName.SZO_134_5, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит5,colorBinding=new Binding("parameterState")},
  [1346]= new ParameterAllValues {parameterName=ParameterName.SZO_134_6, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит6,colorBinding=new Binding("parameterState")},
  [1347]= new ParameterAllValues {parameterName=ParameterName.Ду160_134_7, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит7,colorBinding=new Binding("parameterState")},
  [1348]= new ParameterAllValues {parameterName=ParameterName.Ду160_134_8, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит8,colorBinding=new Binding("parameterState")},
  [1351]= new ParameterAllValues {parameterName=ParameterName.Ду160_135_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
  [1352]= new ParameterAllValues {parameterName=ParameterName.Ду160_135_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
  [1353]= new ParameterAllValues {parameterName=ParameterName.ШтокВВ_135_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
  [1354]= new ParameterAllValues {parameterName=ParameterName.ШтокВН_135_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
  [1355]= new ParameterAllValues {parameterName=ParameterName.РПИ1_135_5, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит5,colorBinding=new Binding("parameterState")},
  [1356]= new ParameterAllValues {parameterName=ParameterName.РПИ2_135_6, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит6,colorBinding=new Binding("parameterState")},
  [1357]= new ParameterAllValues {parameterName=ParameterName.РПИ3_135_7, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит7,colorBinding=new Binding("parameterState")},
  [1358]= new ParameterAllValues {parameterName=ParameterName.РПИ4_135_8, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит8,colorBinding=new Binding("parameterState")},
  [1751]= new ParameterAllValues {parameterName=ParameterName.Ду500_авария_175_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
  [1752]= new ParameterAllValues {parameterName=ParameterName.Ду500_откр_175_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
  [1753]= new ParameterAllValues {parameterName=ParameterName.Ду500_закр_175_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
  [1754]= new ParameterAllValues {parameterName=ParameterName.Ду500_неопредел_175_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
  [1761]= new ParameterAllValues {parameterName=ParameterName.ДВН1500_авария_176_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
  [1762]= new ParameterAllValues {parameterName=ParameterName.ДВН1500_вкл_176_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
  [1763]= new ParameterAllValues {parameterName=ParameterName.ДВН1500_выкл_176_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1771]= new ParameterAllValues {parameterName=ParameterName.ДВН3000_авария_177_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1772]= new ParameterAllValues {parameterName=ParameterName.ДВН3000_вкл_177_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1773]= new ParameterAllValues {parameterName=ParameterName.ДВН3000_выкл_177_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1781]= new ParameterAllValues {parameterName=ParameterName.ARPw_авария_178_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1782]= new ParameterAllValues {parameterName=ParameterName.ARPw_вкл_178_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1783]= new ParameterAllValues {parameterName=ParameterName.ARPw_выкл_178_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1791]= new ParameterAllValues {parameterName=ParameterName.SZO_авария_179_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1792]= new ParameterAllValues {parameterName=ParameterName.SZO_вкл_179_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1793]= new ParameterAllValues {parameterName=ParameterName.SZO_выкл_179_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1801]= new ParameterAllValues {parameterName=ParameterName.Ду160_авария_180_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1802]= new ParameterAllValues {parameterName=ParameterName.Ду160_откр_180_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1803]= new ParameterAllValues {parameterName=ParameterName.Ду160_закр_180_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1804]= new ParameterAllValues {parameterName=ParameterName.Ду160_неопредел_180_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
[1811]= new ParameterAllValues {parameterName=ParameterName.Ду160_авария_181_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1812]= new ParameterAllValues {parameterName=ParameterName.Ду160_откр_181_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1813]= new ParameterAllValues {parameterName=ParameterName.Ду160_закр_181_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1814]= new ParameterAllValues {parameterName=ParameterName.Ду160_неопредел_181_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
[1821]= new ParameterAllValues {parameterName=ParameterName.Ду500_авария_182_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1822]= new ParameterAllValues {parameterName=ParameterName.Ду500_откр_182_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1823]= new ParameterAllValues {parameterName=ParameterName.Ду500_закр_182_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1824]= new ParameterAllValues {parameterName=ParameterName.Ду500_неопредел_182_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
[1831]= new ParameterAllValues {parameterName=ParameterName.ДВН1500_авария_183_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1832]= new ParameterAllValues {parameterName=ParameterName.ДВН1500_вкл_183_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1833]= new ParameterAllValues {parameterName=ParameterName.ДВН1500_выкл_183_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1841]= new ParameterAllValues {parameterName=ParameterName.ДВН3000_авария_184_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1842]= new ParameterAllValues {parameterName=ParameterName.ДВН3000_вкл_184_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1843]= new ParameterAllValues {parameterName=ParameterName.ДВН3000_выкл_184_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1851]= new ParameterAllValues {parameterName=ParameterName.ARPw_авария_185_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1852]= new ParameterAllValues {parameterName=ParameterName.ARPw_вкл_185_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1853]= new ParameterAllValues {parameterName=ParameterName.ARPw_выкл_185_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1861]= new ParameterAllValues {parameterName=ParameterName.SZO_авария_186_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1862]= new ParameterAllValues {parameterName=ParameterName.SZO_вкл_186_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1863]= new ParameterAllValues {parameterName=ParameterName.SZO_выкл_186_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1871]= new ParameterAllValues {parameterName=ParameterName.Ду160_авария_187_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1872]= new ParameterAllValues {parameterName=ParameterName.Ду160_откр_187_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1873]= new ParameterAllValues {parameterName=ParameterName.Ду160_закр_187_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1874]= new ParameterAllValues {parameterName=ParameterName.Ду160_неопредел_187_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
[1881]= new ParameterAllValues {parameterName=ParameterName.Ду160_авария_188_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1882]= new ParameterAllValues {parameterName=ParameterName.Ду160_откр_188_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1883]= new ParameterAllValues {parameterName=ParameterName.Ду160_закр_188_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1884]= new ParameterAllValues {parameterName=ParameterName.Ду160_неопредел_188_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
[1891]= new ParameterAllValues {parameterName=ParameterName.Ду500_авария_189_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1892]= new ParameterAllValues {parameterName=ParameterName.Ду500_откр_189_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1893]= new ParameterAllValues {parameterName=ParameterName.Ду500_закр_189_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1894]= new ParameterAllValues {parameterName=ParameterName.Ду500_неопредел_189_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
[1901]= new ParameterAllValues {parameterName=ParameterName.ДВН1500_авария_190_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1902]= new ParameterAllValues {parameterName=ParameterName.ДВН1500_вкл_190_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1903]= new ParameterAllValues {parameterName=ParameterName.ДВН1500_выкл_190_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1911]= new ParameterAllValues {parameterName=ParameterName.ДВН3000_авария_191_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1912]= new ParameterAllValues {parameterName=ParameterName.ДВН3000_вкл_191_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1913]= new ParameterAllValues {parameterName=ParameterName.ДВН3000_выкл_191_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1921]= new ParameterAllValues {parameterName=ParameterName.ARPw_авария_192_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1922]= new ParameterAllValues {parameterName=ParameterName.ARPw_вкл_192_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1923]= new ParameterAllValues {parameterName=ParameterName.ARPw_выкл_192_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1931]= new ParameterAllValues {parameterName=ParameterName.SZO_авария_193_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1932]= new ParameterAllValues {parameterName=ParameterName.SZO_вкл_193_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1933]= new ParameterAllValues {parameterName=ParameterName.SZO_выкл_193_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1941]= new ParameterAllValues {parameterName=ParameterName.Ду160_авария_194_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1942]= new ParameterAllValues {parameterName=ParameterName.Ду160_откр_194_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1943]= new ParameterAllValues {parameterName=ParameterName.Ду160_закр_194_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1944]= new ParameterAllValues {parameterName=ParameterName.Ду160_неопредел_194_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
[1951]= new ParameterAllValues {parameterName=ParameterName.Ду160_авария_195_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1952]= new ParameterAllValues {parameterName=ParameterName.Ду160_откр_195_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1953]= new ParameterAllValues {parameterName=ParameterName.Ду160_закр_195_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[1954]= new ParameterAllValues {parameterName=ParameterName.Ду160_неопредел_195_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
[1991]= new ParameterAllValues {parameterName=ParameterName.Авария_налич_199_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[1992]= new ParameterAllValues {parameterName=ParameterName.Разр_ВВ_199_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[1993]= new ParameterAllValues {parameterName=ParameterName.Звуковая_199_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[2001]= new ParameterAllValues {parameterName=ParameterName.РПИ5_200_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[2002]= new ParameterAllValues {parameterName=ParameterName.РПИ6_200_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[2003]= new ParameterAllValues {parameterName=ParameterName.РПИ7_200_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[2004]= new ParameterAllValues {parameterName=ParameterName.РПИ8_200_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
[2005]= new ParameterAllValues {parameterName=ParameterName.РПИ9_200_5, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит5,colorBinding=new Binding("parameterState")},
[2006]= new ParameterAllValues {parameterName=ParameterName.РПИ10_200_6, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит6,colorBinding=new Binding("parameterState")},
[2007]= new ParameterAllValues {parameterName=ParameterName.РПИ11_200_7, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит7,colorBinding=new Binding("parameterState")},
[2008]= new ParameterAllValues {parameterName=ParameterName.РПИ12_200_8, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит8,colorBinding=new Binding("parameterState")},
[2011]= new ParameterAllValues {parameterName=ParameterName.РПИ13_201_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[2012]= new ParameterAllValues {parameterName=ParameterName.РПИ14_201_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[2013]= new ParameterAllValues {parameterName=ParameterName.РПИ15_201_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[2014]= new ParameterAllValues {parameterName=ParameterName.РПИ16_201_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
[2015]= new ParameterAllValues {parameterName=ParameterName.ДУ2_201_5, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит5,colorBinding=new Binding("parameterState")},
[2016]= new ParameterAllValues {parameterName=ParameterName.ДУ2_201_6, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит6,colorBinding=new Binding("parameterState")},
[2017]= new ParameterAllValues {parameterName=ParameterName.ДУ3_201_7, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит7,colorBinding=new Binding("parameterState")},
[2018]= new ParameterAllValues {parameterName=ParameterName.ДУ3_201_8, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит8,colorBinding=new Binding("parameterState")},
[2021]= new ParameterAllValues {parameterName=ParameterName.ДУ4_202_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[2022]= new ParameterAllValues {parameterName=ParameterName.ДУ4_202_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[2023]= new ParameterAllValues {parameterName=ParameterName.ДУ5_202_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[2024]= new ParameterAllValues {parameterName=ParameterName.ДУ5_202_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
[2025]= new ParameterAllValues {parameterName=ParameterName.ДУ6_202_5, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит5,colorBinding=new Binding("parameterState")},
[2026]= new ParameterAllValues {parameterName=ParameterName.ДУ6_202_6, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит6,colorBinding=new Binding("parameterState")},
[2028]= new ParameterAllValues {parameterName=ParameterName.Дверь_Б_202_8, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит8,colorBinding=new Binding("parameterState")},
[2031]= new ParameterAllValues {parameterName=ParameterName.Нейтраль_203_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[2032]= new ParameterAllValues {parameterName=ParameterName.Раб_ВН_203_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[2033]= new ParameterAllValues {parameterName=ParameterName.Раб_ВВ_203_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[2034]= new ParameterAllValues {parameterName=ParameterName.Марш_ВН_203_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
[2035]= new ParameterAllValues {parameterName=ParameterName.Марш_ВВ_203_5, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит5,colorBinding=new Binding("parameterState")},
[2036]= new ParameterAllValues {parameterName=ParameterName.КЗ_203_6, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит6,colorBinding=new Binding("parameterState")},
[2037]= new ParameterAllValues {parameterName=ParameterName.Тигель_внизу_203_7, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит7,colorBinding=new Binding("parameterState")},
[2038]= new ParameterAllValues {parameterName=ParameterName.Тигель_вверху_203_8, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит8,colorBinding=new Binding("parameterState")},
[2051]= new ParameterAllValues {parameterName=ParameterName.Первый_диапазон_205_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[2052]= new ParameterAllValues {parameterName=ParameterName.Второй_диапазон_205_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[2053]= new ParameterAllValues {parameterName=ParameterName.Ошибка_вак_1_205_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[2054]= new ParameterAllValues {parameterName=ParameterName.Ошибка_вак_2_205_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
[2061]= new ParameterAllValues {parameterName=ParameterName.Нал_авар_206_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[2062]= new ParameterAllValues {parameterName=ParameterName.Изм_авар_сост_206_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[2063]= new ParameterAllValues {parameterName=ParameterName.Дверь_бокса_206_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[2064]= new ParameterAllValues {parameterName=ParameterName.Ош_кан_тока_206_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},
[2065]= new ParameterAllValues {parameterName=ParameterName.Ош_кан_напр_206_5, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит5,colorBinding=new Binding("parameterState")},
[2066]= new ParameterAllValues {parameterName=ParameterName.Ош_расхода_206_6, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит6,colorBinding=new Binding("parameterState")},
[2067]= new ParameterAllValues {parameterName=ParameterName.Ош_вак_206_7, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит7,colorBinding=new Binding("parameterState")},
[2068]= new ParameterAllValues {parameterName=ParameterName.Вак_откл_206_8, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит8,colorBinding=new Binding("parameterState")},
[2071]= new ParameterAllValues {parameterName=ParameterName.Ош_подпорки_207_1, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит1,colorBinding=new Binding("parameterState")},
[2072]= new ParameterAllValues {parameterName=ParameterName.Авария_водооб_207_2, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит2,colorBinding=new Binding("parameterState")},
[2073]= new ParameterAllValues {parameterName=ParameterName.Ош_натекания_207_3, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит3,colorBinding=new Binding("parameterState")},
[2074]= new ParameterAllValues {parameterName=ParameterName.Ош_времени_207_4, parameterType=ParameterType.дискретный, parameterSize=ParameterSize.ОдинБит,parameterScale=ParameterScale.НеОпределено,bitMask=BitMask.Бит4,colorBinding=new Binding("parameterState")},








				
				
  




  
  
  
  
  
  
  
  
  
  
  
  
  
/*
/*
/*
/*
/*
/*
/*
  
/*
/*
/*
/*
/*
/*
/*
/*
/*
/*
/*
/*
/*
/*
/*
/*
  /*	{2,2}, 
    {4,2}, 
	{6,2}, 
    {8,2},
    {10,2},
    {12,2},
    {14,2},
    {16,2},
    {18,2},
    {20,2},
    {22,2},
    {24,2},
    {26,2},
    {28,2},
    {30,2},
    {32,2},
    {34,2},
    {36,2},
    {38,2},
    {40,2},
    {42,2},
    {44,2},
    {46,2},
    {48,2},
    {50,2},
    {52,2},
    {54,2},
    {56,2},
    {58,2},
    {60,2},
    {62,2},
    {64,2},
    {66,2},
    {68,2},
    {70,2},
    {72,2},
    {74,2},
    {76,2},
    {78,2},
    {80,2},
    {82,2},
    {84,2},
    {86,2},
    {88,2},
    {90,2},
    {92,2},
    {94,2},
    {96,2},
    {98,2},
    {100,2},
    {102,2},
    {104,2},
    {106,2},
    {108,2},
    {110,2},
    {112,2},
    {114,2},
    {116,2},
    {118,2},
    {120,2},
    {122,2},
    {124,2},
    {126,2},
    {128,2} */
};
}	
